### PR TITLE
Fix: Bug in Map marker not getting placed automatically

### PR DESCRIPTION
**Pull request by karnikkanojia**

### CODE REVIEW

**Comment by karnikkanojia** [comment]
@varsharathore16 can you merge this? Just saw the bug.

**Comment by clary09** [comment]
LGTM!

**Review by clary09 — COMMENTED** [review]
LGTM!

**Comment by varsharathore16** [comment]
@karnikkanojia there is still a conflict with the App.js and RequiredThings.js files

**Comment by karnikkanojia** [comment]
@varsharathore16 fixed it 👍

**Comment by varsharathore16** [comment]
@karnikkanojia merged! thanks!

**Pull request merged**
